package com.briup.apps.app01.bean;

public class StudentCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_student_course.id
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_student_course.choose_time
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    private Long chooseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_student_course.grade
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_student_course.student_id
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_student_course.course_id
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    private Long courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_student_course.id
     *
     * @return the value of c_student_course.id
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_student_course.id
     *
     * @param id the value for c_student_course.id
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_student_course.choose_time
     *
     * @return the value of c_student_course.choose_time
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public Long getChooseTime() {
        return chooseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_student_course.choose_time
     *
     * @param chooseTime the value for c_student_course.choose_time
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public void setChooseTime(Long chooseTime) {
        this.chooseTime = chooseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_student_course.grade
     *
     * @return the value of c_student_course.grade
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_student_course.grade
     *
     * @param grade the value for c_student_course.grade
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_student_course.student_id
     *
     * @return the value of c_student_course.student_id
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_student_course.student_id
     *
     * @param studentId the value for c_student_course.student_id
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_student_course.course_id
     *
     * @return the value of c_student_course.course_id
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_student_course.course_id
     *
     * @param courseId the value for c_student_course.course_id
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }
}