package com.briup.apps.app01.bean;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.id
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.realname
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.gender
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.username
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.password
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.type
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.status
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.id
     *
     * @return the value of c_user.id
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.id
     *
     * @param id the value for c_user.id
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.realname
     *
     * @return the value of c_user.realname
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.realname
     *
     * @param realname the value for c_user.realname
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.gender
     *
     * @return the value of c_user.gender
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.gender
     *
     * @param gender the value for c_user.gender
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.username
     *
     * @return the value of c_user.username
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.username
     *
     * @param username the value for c_user.username
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.password
     *
     * @return the value of c_user.password
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.password
     *
     * @param password the value for c_user.password
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.type
     *
     * @return the value of c_user.type
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.type
     *
     * @param type the value for c_user.type
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.status
     *
     * @return the value of c_user.status
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.status
     *
     * @param status the value for c_user.status
     *
     * @mbg.generated Mon Apr 22 20:57:36 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

	@Override
	public String toString() {
		return "User [id=" + id + ", realname=" + realname + ", gender=" + gender + ", username=" + username
				+ ", password=" + password + ", type=" + type + ", status=" + status + "]";
	}
    
}